"""Report generator — HTML/PDF/JSON/JUnit."""
from pathlib import Path
import json
from jinja2 import Environment, FileSystemLoader, select_autoescape

TEMPLATE_DIR = Path(__file__).parent.parent.parent / "resources" / "templates"

def _env():
    # Simple inline template if file missing
    return Environment(autoescape=select_autoescape())

def generate_html(result, path):
    path = Path(path)
    # Critical findings
    findings = ""
    for f in result.failures:
        d = f.diagnose()
        rec = "<br>".join(d.recommendations)
        findings += f"<div class='finding'><b>{f.fault_id}:</b> {d.root_cause} <span class='sev {d.severity}'>{d.severity}</span><div class='rec'>→ {rec}</div></div>"
    if not findings:
        findings = "<p>No critical findings — all faults handled.</p>"
    rows = "".join(f"<tr><td>{r.fault_id}</td><td><span class='{r.status}'>{r.status}</span></td><td>{r.latency_ms or '-'}ms</td><td>{r.recovery_ms or '-'}ms</td><td>{r.safe}</td><td>{r.resilience_index}</td><td>{r.grade}</td></tr>" for r in result.results)
    html = f"""<!DOCTYPE html><html><head><meta charset='utf-8'><title>{result.campaign_name}</title>
<style>
body{{font-family:'Segoe UI',Arial,sans-serif;background:#1E1E2F;color:#E0E0E0;padding:24px;max-width:1100px;margin:auto}}
.card{{background:#2A2A3C;padding:20px;border-radius:12px;display:flex;gap:24px;align-items:center}}
.gauge{{width:120px;height:120px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:700}}
.grade-A{{background:#2ECC71;color:#fff}}.grade-B{{background:#3498DB;color:#fff}}.grade-C{{background:#F1C40F;color:#000}}.grade-D{{background:#E67E22;color:#fff}}.grade-F{{background:#E74C3C;color:#fff}}
.PASS{{color:#4CAF50}}.FAIL{{color:#F44336}}.WARNING{{color:#FF9800}}
table{{width:100%;border-collapse:collapse;margin-top:16px;background:#2A2A3C}}
th,td{{padding:8px;text-align:left;border-bottom:1px solid #3A3A4C}}
.finding{{background:#2A2A3C;padding:12px;border-radius:8px;margin:8px 0;border-left:4px solid #F44336}}
.sev.CRITICAL{{color:#F44336}}.sev.WARNING{{color:#FF9800}}
.rec{{color:#9AA0A6;margin-top:4px;font-family:Consolas,monospace}}
</style></head>
<body><h1>RenodeResilience Report — {result.campaign_name}</h1>
<div class="card"><div class="gauge grade-{result.grade}">{result.resilience_index}</div><div><h2 style="margin:0">Grade {result.grade}</h2><p>Pass {result.pass_count} / Fail {result.fail_count} / Warn {result.warning_count} / Total {result.total_count}</p><p>Formula RI=(D×0.4)+(Rec×0.3)+(S×0.3)</p></div></div>
<h2>Critical Findings</h2>{findings}
<h2>Evidence Table</h2><table><tr><th>ID</th><th>Status</th><th>Detect</th><th>Recover</th><th>Safe</th><th>RI</th><th>Grade</th></tr>{rows}</table>
<p style="color:#9AA0A6;margin-top:24px">Generated by RenodeResilience v1.0 — {result.campaign_name}</p>
</body></html>"""
    path.write_text(html, encoding="utf-8")

def generate_pdf(result, path):
    # Try HTML -> PDF via WeasyPrint, fallback to HTML renamed
    try:
        from weasyprint import HTML
        html_path = Path(path).with_suffix(".html")
        generate_html(result, html_path)
        HTML(filename=str(html_path)).write_pdf(str(path))
    except Exception:
        generate_html(result, Path(path).with_suffix(".html"))

def generate_junit(result, path):
    import xml.etree.ElementTree as ET
    suite = ET.Element("testsuite", name=result.campaign_name, tests=str(result.total_count), failures=str(result.fail_count))
    for r in result.results:
        tc = ET.SubElement(suite, "testcase", classname="fault", name=r.fault_id, time=str((r.latency_ms or 0)/1000))
        if r.status == "FAIL":
            ET.SubElement(tc, "failure", message=f"{r.fault_id} RI {r.resilience_index}")
    tree = ET.ElementTree(suite)
    tree.write(path, encoding="utf-8", xml_declaration=True)
